# Generated by Django 4.0.4 on 2022-05-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('owner_id', models.BigIntegerField(null=True)),
                ('file_id', models.BigIntegerField(null=True)),
                ('imagename', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='requests/')),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('key', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'request_model',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('cpwd', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_register',
            },
        ),
    ]
