# Generated by Django 4.1.3 on 2022-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_usermodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
