# Generated by Django 4.0.4 on 2022-05-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataOwnerModel',
            fields=[
                ('dataowner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('cpwd', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'dataowner_register',
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.BigIntegerField()),
                ('imagename', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('tags', models.CharField(max_length=100)),
                ('encrpyt_key', models.TextField(max_length=500, null=True)),
                ('dataowner_id', models.ForeignKey(blank=True, db_column='dataowner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataownerapp.dataownermodel')),
            ],
            options={
                'db_table': 'owner_uploads',
            },
        ),
    ]
