# Generated by Django 4.0.4 on 2022-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataownerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
