# Generated by Django 4.1.3 on 2022-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataownerapp', '0002_uploadmodel_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='enc_status',
            field=models.CharField(default='Encrypted', max_length=50),
        ),
    ]
