# Generated by Django 4.1.3 on 2022-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataownerapp', '0003_uploadmodel_enc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='file_name_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='image_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='imagename_block',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
